// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PocEconomicsAPI.Models;

public partial class EntrysFeild
{
    [Key]
    public int customerNo { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LastDownload { get; set; }

    [ForeignKey("customerNo")]
    [InverseProperty("EntrysFeild")]
    public virtual Customer customerNoNavigation { get; set; }
}